services:
  ordex-swap:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        BUILD_TEST: ${BUILD_TEST:-false}
    ports:
      - "8080:8080"
    env_file:
      - ./app/.env
    environment:
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - ./app/data:/app/data
    restart: unless-stopped
